version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
